------------------------------------
--------PROJETO FISICO GDI----------

-----------------------------------
-------ENTIDADES REGULARES---------


-- tabela de Usuário
CREATE TABLE USUARIO(
	CPF VARCHAR(15) ,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	TELEFONE1 VARCHAR(10),
	TELEFONE2 VARCHAR(10),
	END_RUA VARCHAR(100),
	END_NUM VARCHAR(100),
	END_CEP VARCHAR(100),
	CPF_CONVIDADO VARCHAR(15),
	CONSTRAINT PK_USUARIO PRIMARY KEY (CPF),
	CONSTRAINT FK_CPF_CONVIDADO FOREIGN KEY (CPF_CONVIDADO) REFERENCES USUARIO(CPF)
);

-- tabela de artista
CREATE TABLE ARTISTA(
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	NOME VARCHAR(100),
	CONSTRAINT PK_ARTISTA PRIMARY KEY (ID)
);

-- tabela de gravadora
CREATE TABLE GRAVADORA(
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	NOME VARCHAR(100),
	CONSTRAINT PK_GRAVADORA PRIMARY KEY (ID)
);

-- tabela de instrumento
CREATE TABLE INSTRUMENTO(
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	NOME VARCHAR(100),
	CONSTRAINT PK_INSTRUMENTO PRIMARY KEY (ID)
);

-- tabela de organização
CREATE TABLE ORGANIZACAO(
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	NOME VARCHAR(100),
	CONSTRAINT PK_ORGANIZACAO PRIMARY KEY (ID)
);

-- tabela de categoria
CREATE TABLE CATEGORIA(
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
	NOME VARCHAR(100),
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
);
------------------------------
-------ENTIDADE FRACA---------

-- tabela de musica
CREATE TABLE MUSICA(
	ID INT,
	NUM INT,
	NOME VARCHAR(100),
	GENERO VARCHAR(100),
	CONSTRAINT PK_MUSICA PRIMARY KEY (ID, NUM),
	CONSTRAINT ID_MUSICA FOREIGN KEY (ID) REFERENCES GRAVADORA ON DELETE CASCADE
);
-------------------------------
-----------HERANÇAS------------
CREATE TABLE ADMIN(

	ID VARCHAR(15),
	CARGO VARCHAR(100),
	CONSTRAINT FK_ID_ADMIN FOREIGN KEY (ID) REFERENCES USUARIO(CPF),
	CONSTRAINT PK_ADMIN PRIMARY KEY (ID)

);

CREATE TABLE COMUM(

	ID VARCHAR(15),
	CONSTRAINT FK_ID_COMUM FOREIGN KEY (ID) REFERENCES USUARIO(CPF),
	CONSTRAINT PK_COMUM PRIMARY KEY (ID)

);
-------------------------------
------ENTIDADE ASSOCIATIVA-----

CREATE TABLE CANTA(
	ID INT,
    NUM INT,
    ID_ART INT,
    CONSTRAINT ID_MUSICA_CANTA FOREIGN KEY (ID,NUM) REFERENCES MUSICA (ID,NUM),
    CONSTRAINT ID_ARTISTA_CANTA FOREIGN KEY (ID_ART) REFERENCES ARTISTA (ID),
	CONSTRAINT PK_CANTA PRIMARY KEY (ID, NUM, ID_ART)
);

-------------------------------
------RELACIONAMENTOS ---------

CREATE TABLE CONSOME(

	CPF VARCHAR(15),
	ID INT,
	NUM INT,
	DATA_ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT CPF_CONSOME FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
	CONSTRAINT ID_MUSICA_CONSOME FOREIGN KEY (ID, NUM) REFERENCES MUSICA(ID,NUM),
	CONSTRAINT PK_CONSOME PRIMARY KEY (CPF,ID)

);

CREATE TABLE TOCA(

	ID_CANTA INT,
	ID_INSTRUMENTO INT,
	ID_MUS INT,
	ID_NUM INT,
	CONSTRAINT FK_ID_CANTA FOREIGN KEY (ID_CANTA,ID_MUS,ID_NUM) REFERENCES CANTA(ID,NUM,ID_ART),
	CONSTRAINT FK_ID_INSTRUMENTO FOREIGN KEY (ID_INSTRUMENTO) REFERENCES INSTRUMENTO(ID),
	CONSTRAINT PK_TOCA PRIMARY KEY (ID_CANTA, ID_INSTRUMENTO)

);

CREATE TABLE GANHA(

	ID_CATEGORIA INT,
	ID_ORGANIZACAO INT,
	DATA_ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ID_MUSICA INT NOT NULL,
	ID_NUM INT NOT NULL,

	CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	CONSTRAINT FK_ID_ORGANIZACAO FOREIGN KEY (ID_ORGANIZACAO) REFERENCES ORGANIZACAO(ID),
	CONSTRAINT NOTNULL_ID_MUSICA FOREIGN KEY (ID_MUSICA,ID_NUM) REFERENCES MUSICA(ID,NUM),
	CONSTRAINT PK_GANHA PRIMARY KEY (ID_CATEGORIA,ID_ORGANIZACAO,DATA_)
);
