------------------------------------
--------PROJETO FISICO GDI----------



-----------------------------------
-------ENTIDADES REGULARES---------


-- tabela de Usuário
CREATE TABLE USUARIO(
	CPF VARCHAR(100),
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	TELEFONE1 VARCHAR(100),
	TELEFONE2 VARCHAR(100),
	END_RUA VARCHAR(100),
	END_NUM VARCHAR(100),
	END_CEP VARCHAR(100),
	CPF_CONVIDADO VARCHAR(100),
	CONSTRAINT PK_USUARIO PRIMARY KEY (CPF),
	CONSTRAINT FK_CPF_CONVIDADO FOREIGN KEY (CPF_CONVIDADO) REFERENCES USUARIO(CPF)
);

-- tabela de artista
CREATE TABLE ARTISTA(
	ID VARCHAR(100),
	NOME VARCHAR(100),
	CONSTRAINT PK_ARTISTA PRIMARY KEY (ID)
);

-- tabela de gravadora
CREATE TABLE GRAVADORA(
	ID VARCHAR(100),
	NOME VARCHAR(100),
	CONSTRAINT PK_GRAVADORA PRIMARY KEY (ID)
);

-- tabela de instrumento
CREATE TABLE INSTRUMENTO(
	ID VARCHAR(100),
	NOME VARCHAR(100),
	CONSTRAINT PK_INSTRUMENTO PRIMARY KEY (ID)
);

-- tabela de organização
CREATE TABLE ORGANIZACAO(
	ID VARCHAR(100),
	NOME VARCHAR(100),
	CONSTRAINT PK_ORGANIZACAO PRIMARY KEY (ID)
);

-- tabela de categoria
CREATE TABLE CATEGORIA(
	ID VARCHAR(100),
	NOME VARCHAR(100),
	CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
);



------------------------------
-------ENTIDADE FRACA---------

-- tabela de musica
CREATE TABLE MUSICA(
	ID VARCHAR(100),
	NUM VARCHAR(100),
	GENERO VARCHAR(100),
	CONSTRAINT PK_MUSICA PRIMARY KEY (ID, NUM),
	CONSTRAINT ID_MUSICA FOREIGN KEY (ID) REFERENCES GRAVADORA ON DELETE CASCADE
);



-------------------------------
-----------HERANÇAS------------

CREATE TABLE ADMIN(

	ID VARCHAR(100),
	CARGO VARCHAR(100),
	CONSTRAINT FK_ID_ADMIN FOREIGN KEY (ID) REFERENCES USUARIO(CPF),
	CONSTRAINT PK_ADMIN PRIMARY KEY (ID)

);

CREATE TABLE COMUM(

	ID VARCHAR(100),
	CONSTRAINT FK_ID_COMUM FOREIGN KEY (ID) REFERENCES USUARIO(CPF),
	CONSTRAINT PK_COMUM PRIMARY KEY (ID)

);




-------------------------------
------ENTIDADE ASSOCIATIVA-----

CREATE TABLE CANTA(
	ID VARCHAR(100),
    NUM VARCHAR(100),
    ID_ART VARCHAR(100),
    CONSTRAINT ID_MUSICA_CANTA FOREIGN KEY (ID,NUM) REFERENCES MUSICA (ID,NUM),
    CONSTRAINT ID_ARTISTA_CANTA FOREIGN KEY (ID_ART) REFERENCES ARTISTA (ID),
	CONSTRAINT PK_CANTA PRIMARY KEY (ID, NUM, ID_ART)
);

-------------------------------
------RELACIONAMENTOS ---------

CREATE TABLE CONSOME(

	CPF VARCHAR(100),
	ID VARCHAR(100),
	NUM VARCHAR(100),
	DATA_ VARCHAR(10),
	CONSTRAINT CPF_CONSOME FOREIGN KEY (CPF) REFERENCES USUARIO(CPF),
	CONSTRAINT ID_MUSICA_CONSOME FOREIGN KEY (ID, NUM) REFERENCES MUSICA(ID,NUM),
	CONSTRAINT PK_CONSOME PRIMARY KEY (CPF,ID)

);

CREATE TABLE TOCA(

	ID_CANTA VARCHAR(100),
	ID_INSTRUMENTO VARCHAR(100),
	ID_MUS VARCHAR(100),
	ID_NUM VARCHAR(100),
	CONSTRAINT FK_ID_CANTA FOREIGN KEY (ID_CANTA,ID_MUS,ID_NUM) REFERENCES CANTA(ID,NUM,ID_ART),
	CONSTRAINT FK_ID_INSTRUMENTO FOREIGN KEY (ID_INSTRUMENTO) REFERENCES INSTRUMENTO(ID),
	CONSTRAINT PK_TOCA PRIMARY KEY (ID_CANTA, ID_INSTRUMENTO)

);

CREATE TABLE GANHA(

	ID_CATEGORIA VARCHAR(100),
	ID_ORGANIZACAO VARCHAR(100),
	DATA_ VARCHAR (100),
	ID_MUSICA VARCHAR(100) NOT NULL,
	ID_NUM VARCHAR(100) NOT NULL,

	CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID),
	CONSTRAINT FK_ID_ORGANIZACAO FOREIGN KEY (ID_ORGANIZACAO) REFERENCES ORGANIZACAO(ID),
	CONSTRAINT NOTNULL_ID_MUSICA FOREIGN KEY (ID_MUSICA,ID_NUM) REFERENCES MUSICA(ID,NUM),
	CONSTRAINT PK_GANHA PRIMARY KEY (ID_CATEGORIA,ID_ORGANIZACAO,DATA_)
);
